name: foodsarv01
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.3
  cupertino_icons: ^1.0.2
  firebase_app_check: ^0.2.1+1
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_storage: ^11.2.8
  location: ^5.0.0
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  otp: ^3.1.4
  permission_handler: ^11.0.1
  syncfusion_flutter_datepicker: ^24.1.44
  uuid: ^4.1.0
  google_maps_widget: ^1.0.5+1
  google_maps_place_picker_mb: ^3.1.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
